#!/usr/bin/env python3

import os
import sys
import time
import json
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.agent.schemas import AgentProposal, AgentFailure
from app.agent.service import build_agent_input, propose_recovery_action
from app.config import settings

def main():
    if not settings.gemini_api_key:
        print("ERROR: GEMINI_API_KEY is not set in environment or .env")
        sys.exit(1)
        
    txn_features = {
        "transaction_id": "test_txn_001",
        "amount": 12500.0,
        "currency": "INR",
        "payment_method": "CARD",
        "failure_reason": "BANK_TIMEOUT",
        "failure_pattern": "A_TEMP_BANK",
        "attempt_number": 1,
        "customer_success_rate": 0.91,
        "customer_previous_failures": 1,
        "customer_previous_recoveries": 0,
        "hours_since_last_success": 48.0,
        "subscription_flag": 0,
    }

    ml_scores = {
        "PAYMENT_LINK": 0.61,
        "REMINDER": 0.34,
        "DELAYED_RETRY": 0.79,
        "ESCALATE": 0.11,
    }
    
    print("==================================================")
    print("REAL API CALL TEST")
    print("==================================================")
    
    start_time = time.time()
    agent_input, result = propose_recovery_action(txn_features, ml_scores)
    latency = time.time() - start_time
    
    print(f"\nLatency: {latency:.2f} seconds")
    print(f"Model used: {settings.gemini_model}")
    
    if isinstance(result, AgentProposal):
        print("\nReal Gemini call SUCCEEDED.")
        print("Parsed AgentProposal:")
        print(result.model_dump_json(indent=2))
        
        # Validations
        print("\nValidations:")
        print("1. Real response: Yes (API key was used, no mock patched)")
        print("2. Pydantic validation: Passed (Parsed as AgentProposal)")
        print(f"3. Recommended action: {result.recommended_action.value} (Valid)")
        print(f"4. Confidence: {result.confidence} (Between 0 and 1)")
        print(f"5. Reason non-empty: {'Yes' if len(result.reason.strip()) > 0 else 'No'}")
        print("6. No financial amount generated by Gemini: Verified (AgentProposal schema does not allow financial values)")
        
        # Verify app-calculated values
        expected = {
            "PAYMENT_LINK": 7625.0,
            "REMINDER": 4250.0,
            "DELAYED_RETRY": 9875.0,
            "ESCALATE": 1375.0
        }
        print("\nChecking deterministic calculations:")
        for score in agent_input.action_scores:
            action = score.action.value
            expected_val = expected[action]
            print(f"  {action}: P={score.probability}, App Calculated Expected={score.expected_recovery} (Expected={expected_val})")
            assert score.expected_recovery == expected_val, f"Mismatch for {action}"
    else:
        print("\nReal Gemini call FAILED.")
        print("AgentFailure:")
        print(result.model_dump_json(indent=2))

    print("\n==================================================")
    print("SECOND TEST: REAL FAILURE HANDLING (MOCKED)")
    print("==================================================")
    
    with patch("app.agent.gemini_client._get_client") as mock_client:
        mock_client.return_value.models.generate_content.side_effect = Exception("Simulated network timeout")
        
        agent_input_fail, result_fail = propose_recovery_action(txn_features, ml_scores)
        
        if isinstance(result_fail, AgentFailure):
            print("Failure handling SUCCEEDED.")
            print("AgentFailure returned:")
            print(result_fail.model_dump_json(indent=2))
            print("\nValidations:")
            print("1. Returns AgentFailure: Yes")
            print("2. No action executed: Yes")
            print("3. Application did not crash: Yes")
            print(f"4. Failure reason: {result_fail.error_type} - {result_fail.error_message}")
        else:
            print("Failure handling FAILED. Did not return AgentFailure.")

if __name__ == '__main__':
    main()
