"""initial_schema

Revision ID: 5220445bcea9
Revises: 
Create Date: 2026-08-21 18:38:07.874544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5220445bcea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recovery_policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('successful_payment_count', sa.Integer(), nullable=False),
    sa.Column('failed_payment_count', sa.Integer(), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_merchant_external', 'customers', ['merchant_id', 'external_customer_id'], unique=True)
    op.create_index('ix_customers_merchant_id', 'customers', ['merchant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NET_BANKING', 'WALLET', 'EMI', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_customer_id', 'payments', ['customer_id'], unique=False)
    op.create_index('ix_payments_merchant_id', 'payments', ['merchant_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('payment_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('failure_source', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_event_reference', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index('ix_payment_failures_payment_id', 'payment_failures', ['payment_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RECOVERED', 'FAILED', 'EXPIRED', 'ESCALATED', 'STOPPED', name='recovery_case_status'), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('eligibility_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index('ix_recovery_cases_created_at', 'recovery_cases', ['created_at'], unique=False)
    op.create_index('ix_recovery_cases_payment_id', 'recovery_cases', ['payment_id'], unique=False)
    op.create_index('ix_recovery_cases_status', 'recovery_cases', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'ML_MODEL', 'LLM_AGENT', 'POLICY_ENGINE', 'HUMAN', name='audit_actor_type'), nullable=False),
    sa.Column('actor_name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('policy_result', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_case_id', 'audit_logs', ['recovery_case_id'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('PAYMENT_LINK', 'REMINDER', 'ESCALATE', 'DELAYED_RETRY', name='recovery_action_type'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'POLICY_BLOCKED', 'APPROVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='recovery_action_status'), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('expected_recovery', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_net_recovery', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_actions_case_id', 'recovery_actions', ['recovery_case_id'], unique=False)
    op.create_index('ix_recovery_actions_status', 'recovery_actions', ['status'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('outcome_type', sa.Enum('RECOVERED', 'FAILED', 'EXPIRED', 'ESCALATED', 'STOPPED', name='outcome_type'), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id'),
    sa.UniqueConstraint('recovery_case_id')
    )
    op.create_index('ix_recovery_outcomes_case_id', 'recovery_outcomes', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_outcomes_case_id', table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index('ix_recovery_actions_status', table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_case_id', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_case_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_recovery_cases_status', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_payment_id', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_created_at', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index('ix_payment_failures_payment_id', table_name='payment_failures')
    op.drop_table('payment_failures')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_merchant_id', table_name='payments')
    op.drop_index('ix_payments_customer_id', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_customers_merchant_id', table_name='customers')
    op.drop_index('ix_customers_merchant_external', table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
