"""add_payment_link_url_to_recovery_actions

Revision ID: c8082eead98f
Revises: 5220445bcea9
Create Date: 2026-09-01 19:45:14.676921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8082eead98f'
down_revision: Union[str, None] = '5220445bcea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_actions', sa.Column('payment_link_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_actions', 'payment_link_url')
    # ### end Alembic commands ###
